<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DirectoryService.SharedKernel\DirectoryService.SharedKernel.csproj" />
  </ItemGroup>
    
</Project>
