<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>CA1716;RCS1194;CA1032;CA2225</NoWarn>
    </PropertyGroup>
    
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DirectoryService.Shared</RootNamespace>
    </PropertyGroup>

</Project>
