<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>CA1848,CA1873, S112, CA2201, CA1711, S2166,RCS1194, CA1032</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DirectoryService.SharedKernel\DirectoryService.SharedKernel.csproj" />
    <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
    <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
  </ItemGroup>

</Project>
